"""stage2 masters inventory tables

Revision ID: 29a15444c917
Revises: d4b8a759d275
Create Date: 2026-08-19 18:42:04.412472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a15444c917'
down_revision: Union[str, Sequence[str], None] = 'd4b8a759d275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_settings_key'))
    )
    op.create_table('inventory_on_hand',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_inventory_on_hand_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_on_hand_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_on_hand')),
    sa.UniqueConstraint('business_unit_id', 'product_id', name='uq_inventory_on_hand_bu_product')
    )
    op.create_table('inventory_on_order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('booking_status', sa.Enum("PO'ed", "Book'ed", name='bookingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_inventory_on_order_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_on_order_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_on_order'))
    )
    op.create_table('lead_times',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.CheckConstraint('months > 0', name=op.f('ck_lead_times_months_positive')),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_lead_times_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_lead_times_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_times'))
    )
    op.create_table('safety_stocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_safety_stocks_quantity_non_negative')),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_safety_stocks_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_safety_stocks_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_stocks')),
    sa.UniqueConstraint('business_unit_id', 'product_id', name='uq_safety_stocks_bu_product')
    )
    op.create_table('technical_substitutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_product_id', sa.String(length=36), nullable=False),
    sa.Column('to_product_id', sa.String(length=36), nullable=False),
    sa.CheckConstraint('from_product_id != to_product_id', name=op.f('ck_technical_substitutions_from_ne_to')),
    sa.ForeignKeyConstraint(['from_product_id'], ['products.id'], name=op.f('fk_technical_substitutions_from_product_id_products')),
    sa.ForeignKeyConstraint(['to_product_id'], ['products.id'], name=op.f('fk_technical_substitutions_to_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_substitutions')),
    sa.UniqueConstraint('from_product_id', 'to_product_id', name='uq_technical_substitutions_from_to')
    )
    op.create_table('customer_owned_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_owned_inventory_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_customer_owned_inventory_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_owned_inventory')),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_customer_owned_inventory_customer_product')
    )
    op.create_table('customer_owned_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_owned_uploads_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_owned_uploads'))
    )
    op.create_table('customer_substitution_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('technical_substitution_id', sa.String(length=36), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_substitution_rules_customer_id_customers')),
    sa.ForeignKeyConstraint(['technical_substitution_id'], ['technical_substitutions.id'], name=op.f('fk_customer_substitution_rules_technical_substitution_id_technical_substitutions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_substitution_rules')),
    sa.UniqueConstraint('customer_id', 'technical_substitution_id', name='uq_customer_substitution_rules_customer_substitution')
    )
    op.create_table('inventory_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_inventory_assignments_business_unit_id_business_units')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_inventory_assignments_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_assignments_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_assignments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_assignments')
    op.drop_table('customer_substitution_rules')
    op.drop_table('customer_owned_uploads')
    op.drop_table('customer_owned_inventory')
    op.drop_table('technical_substitutions')
    op.drop_table('safety_stocks')
    op.drop_table('lead_times')
    op.drop_table('inventory_on_order')
    op.drop_table('inventory_on_hand')
    op.drop_table('settings')
    # ### end Alembic commands ###
