"""stage6 scenario models

Revision ID: 4544b6337278
Revises: a6df450e57d9
Create Date: 2026-08-19 21:41:52.126036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4544b6337278'
down_revision: Union[str, Sequence[str], None] = 'a6df450e57d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Applied', name='scenariostatus'), server_default='Draft', nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    op.create_table('scenario_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('quantity', 'ros_date', 'well_status', 'po_arrival', 'hard_release', 'approval_flip', name='scenariooverridekind'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_overrides_scenario_id_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_overrides'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_overrides')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
