"""stage3 demand models

Revision ID: 656cb67915c2
Revises: 132101af1ae0
Create Date: 2026-08-19 19:26:49.860385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '656cb67915c2'
down_revision: Union[str, Sequence[str], None] = '132101af1ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'discarded', name='demandimportstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_demand_imports_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_imports'))
    )
    op.create_table('wells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('demand_status', sa.Enum('Planned', 'Budgeted', 'Confirmed', name='demandstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_wells_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wells')),
    sa.UniqueConstraint('customer_id', 'name', name='uq_wells_customer_id_name')
    )
    op.create_table('demand_import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('well_name', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('ros_date', sa.Date(), nullable=False),
    sa.Column('profile', sa.Enum('Primary', 'Contingency', name='demandprofile'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['demand_imports.id'], name=op.f('fk_demand_import_rows_import_id_demand_imports')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_demand_import_rows_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_import_rows'))
    )
    op.create_table('demand_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('well_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('ros_date', sa.Date(), nullable=False),
    sa.Column('profile', sa.Enum('Primary', 'Contingency', name='demandprofile'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_demand_lines_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_demand_lines_product_id_products')),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], name=op.f('fk_demand_lines_well_id_wells')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_lines'))
    )
    op.create_table('demand_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('well_id', sa.String(length=36), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('import', 'manual', 'status_change', name='demandrevisionsource'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], name=op.f('fk_demand_revisions_well_id_wells')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_revisions')),
    sa.UniqueConstraint('well_id', 'revision_no', name='uq_demand_revisions_well_id_revision_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand_revisions')
    op.drop_table('demand_lines')
    op.drop_table('demand_import_rows')
    op.drop_table('wells')
    op.drop_table('demand_imports')
    # ### end Alembic commands ###
