"""initial schema

Baseline migration: the FULL current schema, autogenerated from
``app.models`` and then reviewed by hand.

Hand corrections applied to the autogenerated output
----------------------------------------------------
Autogenerate emitted a bare ``sa.Enum(..., name='demandstatus')`` inside BOTH
``demand_lines`` and ``demand_revisions`` (and likewise ``demandprofile``). On
sqlite that is harmless -- an enum is just VARCHAR + CHECK -- but on postgres
each ``create_table`` would emit its own ``CREATE TYPE demandstatus``, and the
second one raises ``DuplicateObject``. Since ``DATABASE_URL`` defaults to
postgres, that would have made this migration unrunnable in production.

The fix: every enum is declared ONCE as a module-level object with a postgres
variant carrying ``create_type=False``, and the types are created (and dropped)
explicitly, once, at the top of ``upgrade()`` / bottom of ``downgrade()``.
sqlite behaviour is byte-for-byte unchanged.

Revision ID: 7ebf91b5526c
Revises:
Create Date: 2026-08-04 17:30:28.568594

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ebf91b5526c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(*values: str, name: str) -> sa.Enum:
    """Portable enum whose postgres variant never auto-creates its type.

    The type itself is created once by ``_create_enum_types``; leaving
    ``create_type`` at its default would make every ``create_table`` that
    mentions the enum try to create it again.
    """
    return sa.Enum(*values, name=name).with_variant(
        postgresql.ENUM(*values, name=name, create_type=False), "postgresql"
    )


ALLOCATION_POLICY = _enum('SOFT', 'HARD', 'HYBRID', name='allocationpolicy')
DEMAND_STATUS = _enum('PLANNED', 'BUDGETED', 'CONFIRMED', name='demandstatus')
DEMAND_PROFILE = _enum('PRIMARY', 'CONTINGENCY', name='demandprofile')
COVERAGE_STATUS = _enum(
    'COVERED', 'COVERED_VIA_SUBSTITUTE', 'PENDING_APPROVAL', 'UNCOVERED',
    'UNRECOVERABLE', name='coveragestatus',
)
SUBSTITUTION_APPROVAL_STATUS = _enum(
    'APPROVED', 'PENDING', 'REJECTED', name='substitutionapprovalstatus'
)

_ENUMS = (
    ('allocationpolicy', ('SOFT', 'HARD', 'HYBRID')),
    ('demandstatus', ('PLANNED', 'BUDGETED', 'CONFIRMED')),
    ('demandprofile', ('PRIMARY', 'CONTINGENCY')),
    (
        'coveragestatus',
        (
            'COVERED', 'COVERED_VIA_SUBSTITUTE', 'PENDING_APPROVAL',
            'UNCOVERED', 'UNRECOVERABLE',
        ),
    ),
    ('substitutionapprovalstatus', ('APPROVED', 'PENDING', 'REJECTED')),
)


def _create_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return  # sqlite has no standalone enum types
    for name, values in _ENUMS:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)


def _drop_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return
    for name, values in _ENUMS:
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    _create_enum_types()

    op.create_table('business_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_time_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grade_type', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('months', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('grade_type', sa.String(), nullable=False),
    sa.Column('connection', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('on_hand_qty', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('allocation_policy', ALLOCATION_POLICY, nullable=False),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_on_hand',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_unit_id', 'product_id', name='uq_inventory_on_hand_bu_product')
    )
    op.create_table('technical_substitutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_product_id', sa.String(length=36), nullable=False),
    sa.Column('to_product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['from_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_substitution_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('from_product_id', sa.String(length=36), nullable=False),
    sa.Column('to_product_id', sa.String(length=36), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['from_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['planning_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planning_node_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('coverage_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['planning_node_id'], ['planning_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('well_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ros_date', sa.DateTime(), nullable=False),
    sa.Column('status', DEMAND_STATUS, nullable=False),
    sa.Column('profile', DEMAND_PROFILE, nullable=False),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_results',
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('status', COVERAGE_STATUS, nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('fulfilled_by_product_id', sa.String(length=36), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_by_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('demand_line_id')
    )
    op.create_table('demand_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('ros_date', sa.DateTime(), nullable=False),
    sa.Column('status', DEMAND_STATUS, nullable=False),
    sa.Column('profile', DEMAND_PROFILE, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('well_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_before', sa.Float(), nullable=True),
    sa.Column('quantity_after', sa.Float(), nullable=True),
    sa.Column('ros_date_before', sa.DateTime(), nullable=True),
    sa.Column('ros_date_after', sa.DateTime(), nullable=True),
    sa.Column('status_before', sa.String(), nullable=True),
    sa.Column('status_after', sa.String(), nullable=True),
    sa.Column('coverage_before', sa.String(), nullable=True),
    sa.Column('coverage_after', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('well_substitution_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('from_product_id', sa.String(length=36), nullable=False),
    sa.Column('to_product_id', sa.String(length=36), nullable=False),
    sa.Column('status', SUBSTITUTION_APPROVAL_STATUS, nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], ),
    sa.ForeignKeyConstraint(['from_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema -- drops everything this revision created, children
    before parents, and the postgres enum types last."""
    op.drop_table('well_substitution_approvals')
    op.drop_table('inventory_assignments')
    op.drop_table('impact_records')
    op.drop_table('demand_revisions')
    op.drop_table('coverage_results')
    op.drop_table('demand_lines')
    op.drop_table('wells')
    op.drop_table('planning_nodes')
    op.drop_table('customer_substitution_rules')
    op.drop_table('technical_substitutions')
    op.drop_table('inventory_on_hand')
    op.drop_table('customers')
    op.drop_table('products')
    op.drop_table('lead_time_components')
    op.drop_table('business_units')

    _drop_enum_types()
