"""stage4 coverage and substitution approval models

Revision ID: a6df450e57d9
Revises: 656cb67915c2
Create Date: 2026-08-19 19:58:21.710060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6df450e57d9'
down_revision: Union[str, Sequence[str], None] = '656cb67915c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.Enum('Covered', 'CoveredViaSubstitute', 'PendingApproval', 'Uncovered', 'Unrecoverable', name='coverageverdict'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('covered_qty', sa.Float(), nullable=False),
    sa.Column('covered_via', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], name=op.f('fk_coverage_results_demand_line_id_demand_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_results')),
    sa.UniqueConstraint('demand_line_id', name='uq_coverage_results_demand_line_id')
    )
    op.create_table('substitution_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('well_id', sa.String(length=36), nullable=False),
    sa.Column('demand_line_id', sa.String(length=36), nullable=False),
    sa.Column('technical_substitution_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='substitutionapprovalstatus'), server_default='Pending', nullable=False),
    sa.Column('customer_approved', sa.Boolean(), nullable=False),
    sa.Column('well_approved', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_substitution_approvals_customer_id_customers')),
    sa.ForeignKeyConstraint(['demand_line_id'], ['demand_lines.id'], name=op.f('fk_substitution_approvals_demand_line_id_demand_lines')),
    sa.ForeignKeyConstraint(['technical_substitution_id'], ['technical_substitutions.id'], name=op.f('fk_substitution_approvals_technical_substitution_id_technical_substitutions')),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], name=op.f('fk_substitution_approvals_well_id_wells')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substitution_approvals'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'allocation_policy',
                sa.Enum('SOFT', 'HARD', 'HYBRID', name='allocationpolicy'),
                server_default='SOFT',
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('allocation_policy')
    op.drop_table('substitution_approvals')
    op.drop_table('coverage_results')
    # ### end Alembic commands ###
