"""demand import staging tables

Adds the Excel demand-import staging area: ``demand_import_batches`` and
``demand_import_rows`` (see app.models.demand_import). Purely ADDITIVE -- two new
tables, no ALTER of any existing table -- so it is safe to run against a database
a dev server currently holds open.

Hand corrections applied to the autogenerated output
----------------------------------------------------
Autogenerate emitted bare ``sa.Enum(..., name=...)`` inline in the ``create_table``
calls. That is the trap this project has already been bitten by (see
``7ebf91b5526c_initial_schema.py``): on postgres each inline enum makes
``create_table`` emit its own ``CREATE TYPE``, and a second one raises
``DuplicateObject``. ``DATABASE_URL`` defaults to postgres, so the raw output
would have been unrunnable in production.

Two distinct problems, two distinct fixes:

  * THREE NEW types (``demandimportbatchstatus``, ``demandimportmatchtype``,
    ``demandimportdecision``) are declared once as module-level objects with a
    postgres variant carrying ``create_type=False``, and created explicitly at the
    top of ``upgrade()`` / dropped at the bottom of ``downgrade()``.

  * TWO PRE-EXISTING types (``demandstatus``, ``demandprofile``) are referenced by
    ``demand_import_rows``. They were created by the initial migration and are
    still in use by ``demand_lines`` / ``demand_revisions``, so this revision must
    neither create nor drop them -- creating would raise ``DuplicateObject`` on
    upgrade, and dropping would raise ``DependentObjectsStillExist`` on downgrade
    (or, worse, succeed and take the demand tables' types with it). They are
    referenced through the same ``create_type=False`` variant and are absent from
    ``_NEW_ENUMS`` on purpose.

sqlite behaviour is unaffected either way -- an enum there is just VARCHAR plus a
CHECK constraint, and sqlite has no standalone enum types to duplicate.

Revision ID: b7f4c1a92e30
Revises: c4f1a90b7de2
Create Date: 2026-08-04 17:52:00.000000

Chaining note
-------------
Two feature branches added a migration on top of the initial schema at the same
time. Rather than leave two heads (or merge them, which is unnecessary here) this
revision is chained AFTER the scenario-planning revision c4f1a90b7de2, giving a
single linear history. Order between the two is immaterial: both are purely
additive and create disjoint sets of new tables with no shared foreign keys.

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7f4c1a92e30'
down_revision: Union[str, Sequence[str], None] = 'c4f1a90b7de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(*values: str, name: str) -> sa.Enum:
    """Portable enum whose postgres variant never auto-creates its type.

    Used for BOTH the new types (created once by ``_create_enum_types``) and the
    pre-existing ones (already created by the initial migration). In neither case
    may ``create_table`` create the type itself.
    """
    return sa.Enum(*values, name=name).with_variant(
        postgresql.ENUM(*values, name=name, create_type=False), "postgresql"
    )


# Types this revision OWNS: created on upgrade, dropped on downgrade.
_NEW_ENUMS = (
    ('demandimportbatchstatus', ('STAGED', 'APPLIED')),
    ('demandimportmatchtype', ('REVISION', 'NEW', 'ERROR')),
    (
        'demandimportdecision',
        ('PENDING', 'ACCEPT_REVISION', 'ACCEPT_NEW', 'SKIP'),
    ),
)

DEMAND_IMPORT_BATCH_STATUS = _enum('STAGED', 'APPLIED', name='demandimportbatchstatus')
DEMAND_IMPORT_MATCH_TYPE = _enum(
    'REVISION', 'NEW', 'ERROR', name='demandimportmatchtype'
)
DEMAND_IMPORT_DECISION = _enum(
    'PENDING', 'ACCEPT_REVISION', 'ACCEPT_NEW', 'SKIP', name='demandimportdecision'
)

# Types owned by 7ebf91b5526c. Referenced only -- NEVER created or dropped here.
DEMAND_STATUS = _enum('PLANNED', 'BUDGETED', 'CONFIRMED', name='demandstatus')
DEMAND_PROFILE = _enum('PRIMARY', 'CONTINGENCY', name='demandprofile')


def _create_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return  # sqlite has no standalone enum types
    for name, values in _NEW_ENUMS:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)


def _drop_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return
    for name, values in _NEW_ENUMS:
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    _create_enum_types()

    op.create_table(
        'demand_import_batches',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('sheet_name', sa.String(), nullable=True),
        sa.Column('status', DEMAND_IMPORT_BATCH_STATUS, nullable=False),
        sa.Column('row_count', sa.Integer(), nullable=False),
        sa.Column('error_count', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('applied_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'demand_import_rows',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('batch_id', sa.String(length=36), nullable=False),
        sa.Column('row_number', sa.Integer(), nullable=False),
        sa.Column('raw_well', sa.String(), nullable=True),
        sa.Column('raw_product', sa.String(), nullable=True),
        sa.Column('raw_quantity', sa.String(), nullable=True),
        sa.Column('raw_ros_date', sa.String(), nullable=True),
        sa.Column('raw_status', sa.String(), nullable=True),
        sa.Column('raw_profile', sa.String(), nullable=True),
        sa.Column('well_id', sa.String(length=36), nullable=True),
        sa.Column('product_id', sa.String(length=36), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('ros_date', sa.DateTime(), nullable=True),
        sa.Column('status', DEMAND_STATUS, nullable=True),
        sa.Column('profile', DEMAND_PROFILE, nullable=True),
        sa.Column('match_type', DEMAND_IMPORT_MATCH_TYPE, nullable=False),
        sa.Column('matched_demand_line_id', sa.String(length=36), nullable=True),
        sa.Column('match_reason', sa.String(), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('decision', DEMAND_IMPORT_DECISION, nullable=False),
        sa.Column('applied', sa.Boolean(), nullable=False),
        sa.Column('applied_demand_line_id', sa.String(length=36), nullable=True),
        sa.Column('apply_error', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['applied_demand_line_id'], ['demand_lines.id'], ),
        sa.ForeignKeyConstraint(['batch_id'], ['demand_import_batches.id'], ),
        sa.ForeignKeyConstraint(['matched_demand_line_id'], ['demand_lines.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade() -> None:
    """Downgrade schema -- children before parents, then only the enum types
    this revision created.

    ``demandstatus`` and ``demandprofile`` are deliberately NOT dropped: they
    belong to 7ebf91b5526c and ``demand_lines`` / ``demand_revisions`` still use
    them.
    """
    op.drop_table('demand_import_rows')
    op.drop_table('demand_import_batches')

    _drop_enum_types()
