"""scenario planning

Adds the two Phase 4 tables: ``scenarios`` and ``scenario_overrides``. See
app.models.scenario for the shape and the reasoning behind ONE polymorphic
override table.

PURELY ADDITIVE
---------------
Two new tables, two new postgres enum types, and nothing else. No existing table
is altered and no existing column is touched, so this migration is safe to run
against a database an application server is holding open.

Hand corrections applied to the autogenerated output
----------------------------------------------------
The known autogenerate trap in this project (see
``7ebf91b5526c_initial_schema.py``) is that alembic emits a bare
``sa.Enum(..., name=...)`` inline in every ``create_table`` that mentions it. On
sqlite that is harmless -- an enum is VARCHAR + CHECK -- but on postgres each one
emits its own ``CREATE TYPE`` and the second raises ``DuplicateObject``. Since
``DATABASE_URL`` defaults to postgres, that would make the migration unrunnable
in production.

The same fix is applied here even though each of the two new enums is currently
mentioned by exactly one table, so the pattern holds if a later table reuses
either of them: every enum is declared ONCE as a module-level object whose
postgres variant carries ``create_type=False``, and the types are created (and
dropped) explicitly, once, at the top of ``upgrade()`` / bottom of
``downgrade()``. sqlite behaviour is byte-for-byte unchanged.

Enum MEMBER NAMES, not values, are stored -- matching every other enum column in
this schema (SQLAlchemy's ``Enum`` default for a python ``enum.Enum``). So
``scenariostatus`` holds 'DRAFT', not 'Draft'.

Revision ID: c4f1a90b7de2
Revises: 7ebf91b5526c
Create Date: 2026-08-04 17:52:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4f1a90b7de2'
down_revision: Union[str, Sequence[str], None] = '7ebf91b5526c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(*values: str, name: str) -> sa.Enum:
    """Portable enum whose postgres variant never auto-creates its type.

    The type itself is created once by ``_create_enum_types``; leaving
    ``create_type`` at its default would make every ``create_table`` that
    mentions the enum try to create it again.
    """
    return sa.Enum(*values, name=name).with_variant(
        postgresql.ENUM(*values, name=name, create_type=False), "postgresql"
    )


SCENARIO_STATUS = _enum(
    'DRAFT', 'REVIEW', 'DISCUSSION', 'APPLIED', name='scenariostatus'
)
SCENARIO_TARGET_KIND = _enum(
    'DEMAND_LINE', 'INVENTORY', 'PO_ARRIVAL', 'ASSIGNMENT',
    'SUBSTITUTION_APPROVAL', name='scenariotargetkind',
)

_ENUMS = (
    ('scenariostatus', ('DRAFT', 'REVIEW', 'DISCUSSION', 'APPLIED')),
    (
        'scenariotargetkind',
        (
            'DEMAND_LINE', 'INVENTORY', 'PO_ARRIVAL', 'ASSIGNMENT',
            'SUBSTITUTION_APPROVAL',
        ),
    ),
)


def _create_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return  # sqlite has no standalone enum types
    for name, values in _ENUMS:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)


def _drop_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != 'postgresql':
        return
    for name, values in _ENUMS:
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    """Upgrade schema."""
    _create_enum_types()

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('status', SCENARIO_STATUS, nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('target_kind', SCENARIO_TARGET_KIND, nullable=False),
    sa.Column('target_demand_line_id', sa.String(length=36), nullable=True),
    sa.Column('target_product_id', sa.String(length=36), nullable=True),
    sa.Column('target_business_unit_id', sa.String(length=36), nullable=True),
    sa.Column('target_assignment_id', sa.String(length=36), nullable=True),
    sa.Column('target_approval_id', sa.String(length=36), nullable=True),
    sa.Column('target_from_product_id', sa.String(length=36), nullable=True),
    sa.Column('target_to_product_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['target_approval_id'], ['well_substitution_approvals.id'], ),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['inventory_assignments.id'], ),
    sa.ForeignKeyConstraint(['target_business_unit_id'], ['business_units.id'], ),
    sa.ForeignKeyConstraint(['target_demand_line_id'], ['demand_lines.id'], ),
    sa.ForeignKeyConstraint(['target_from_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['target_to_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema -- children before parents, postgres enum types last."""
    op.drop_table('scenario_overrides')
    op.drop_table('scenarios')

    _drop_enum_types()
