"""customer-owned inventory -- the first inventory table THIS platform owns

Adds TWO tables:

  ``customer_owned_inventory_uploads``  one accepted spreadsheet per row. It is the
                                       audit trail AND the fact that an upload has
                                       happened at all, which is what keeps "this
                                       customer owns none of product P" apart from
                                       "nobody has ever told us what they own".
  ``customer_owned_inventory``          one declared position per (customer, product).

See ``app.models.customer_owned_inventory`` for the shape, for why the Business Unit
is deliberately NOT a column here (a customer belongs to exactly one BU, so the BU is
derivable, and a denormalised copy would go stale the moment a customer is remapped
with no defensible way to resolve the disagreement), and -- most importantly -- for
why this table is NOT a read-only Oracle projection like every other inventory table
in this schema.

PURELY ADDITIVE
---------------
Two new tables. No existing table is altered, no existing column is touched and no
data is migrated, so this is safe to run against a database an application server is
holding open. There is nothing to back-fill and nothing that COULD be back-filled:
customer-owned inventory has never existed anywhere in this platform, and Oracle does
not hold it either, so inventing rows here would fabricate a customer's declared
stock position.

NO NEW ENUM TYPE, AND NO DUPLICATE-TYPE TRAP
--------------------------------------------
The known autogenerate trap in this project (see ``7ebf91b5526c_initial_schema``,
``c4f1a90b7de2_scenario_planning`` and ``b7f4c1a92e30_demand_import_staging``) is that
alembic emits a bare ``sa.Enum(..., name=...)`` inline in every ``create_table`` that
mentions it, which on postgres makes the SECOND such table raise ``DuplicateObject``.
``DATABASE_URL`` defaults to postgres, so raw autogenerated output carrying two
inline enums would be unrunnable in production.

It cannot bite here, and that is a design decision rather than luck. Neither table
declares an enum column:

  * ``source_system`` is a plain ``String`` carrying a provenance vocabulary, exactly
    as ``inventory_on_hand``, ``inventory_on_order`` and ``inventory_assignments``
    already do. The vocabulary here is "customer-upload" / "synthetic" / "mixed" /
    "declared-none" / "unavailable", and the last two are values NO ROW can hold --
    they are computed by ``app.engines.inventory`` to describe an absence. A database
    enum would either have to include values that cannot occur in the column or
    disagree with the API's own vocabulary; a String does neither.
  * The upload flow has NO status enum because it has no staging step to have a status
    for. An inventory position is replaced, not adjudicated, so there is no
    ``Staged`` / ``Applied`` lifecycle -- see ``app.engines.customer_owned_import``.
    ``demand_import`` needed three enum types precisely because it has a review flow;
    this one does not, and copying its shape would have imported the trap along with
    it.

Consequently ``_create_enum_types`` / ``_drop_enum_types`` are absent from this
revision because there is genuinely nothing for them to do.

UNIQUE CONSTRAINT ON (customer_id, product_id)
----------------------------------------------
Like ``inventory_on_hand``'s constraint on (BU, product) and UNLIKE
``inventory_on_order``, where one row is one expected arrival and several per pair are
the correct shape of a delivery schedule. Here the pair IS the fact: a customer owns
one quantity of one product, which is what makes an upload a REPLACEMENT of that
single row rather than an append. Without the constraint a re-upload bug would
silently double a customer's declared stock, and a doubled position is a well that
does not get its pipe.

Revision ID: c8e37b45d1a0
Revises: b1d9e04f7a52
Create Date: 2026-08-05 14:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8e37b45d1a0'
down_revision: Union[str, Sequence[str], None] = 'b1d9e04f7a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the upload table, then the position table that references it."""
    op.create_table(
        'customer_owned_inventory_uploads',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('customer_id', sa.String(length=36), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('sheet_name', sa.String(), nullable=True),
        sa.Column('row_count', sa.Integer(), nullable=False),
        sa.Column('applied_count', sa.Integer(), nullable=False),
        sa.Column('error_count', sa.Integer(), nullable=False),
        sa.Column('replaced_count', sa.Integer(), nullable=False),
        sa.Column('created_count', sa.Integer(), nullable=False),
        sa.Column(
            'uploaded_at',
            sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            nullable=False,
        ),
        sa.Column('source_system', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'customer_owned_inventory',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('customer_id', sa.String(length=36), nullable=False),
        sa.Column('product_id', sa.String(length=36), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('source_system', sa.String(), nullable=False),
        sa.Column('source_reference', sa.String(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('upload_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(
            ['upload_id'], ['customer_owned_inventory_uploads.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'customer_id',
            'product_id',
            name='uq_customer_owned_inventory_customer_product',
        ),
    )


def downgrade() -> None:
    """Drop both tables, positions first (it references the uploads table).

    A real downgrade, not a ``pass``.

    ################################################################
    #  IT DESTROYS DATA THAT HAS NO OTHER SOURCE. READ THIS.        #
    ################################################################

    Every other downgrade in this project's history can say "the rows are a read-only
    projection of Oracle-owned data, so re-run the feed". ``b1d9e04f7a52`` says exactly
    that about ``inventory_on_order``, and it is true there.

    IT IS NOT TRUE HERE, and the difference is the whole reason this table exists.
    Oracle holds only OUR OWN company's inventory. Customer-owned material is absent
    from it entirely -- there is no feed to re-run, no upstream row to re-project and
    no other system that could be asked. Each quantity here came from a spreadsheet a
    human produced and sent, and dropping these tables loses:

      * every customer's declared position, until somebody finds the file again;
      * the FACT THAT AN UPLOAD EVER HAPPENED, which is what
        ``app.engines.inventory.customer_owned_map`` uses to report "owns none" rather
        than "no data". After a downgrade every customer reads as UNKNOWN again, which
        is at least honest -- but it is honest about having lost the data, not about
        the customer owning nothing.

    Coverage will still compute after a downgrade (nothing here raises on absence, by
    design), so THE LOSS IS SILENT: verdicts simply move, because the tier that used
    to be drawn first is gone. Re-running ``upgrade`` restores the schema and nothing
    else. If the data matters, back these two tables up before downgrading, or
    re-upload every customer's spreadsheet afterwards.

    ``python -m seed.seed_from_workbook --reset`` rebuilds the SYNTHETIC demo
    positions only. It knows nothing about a real customer's file.
    """
    op.drop_table('customer_owned_inventory')
    op.drop_table('customer_owned_inventory_uploads')
