"""initial master tables

Revision ID: d4b8a759d275
Revises: 
Create Date: 2026-08-19 15:49:58.852983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b8a759d275'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['business_units.id'], name=op.f('fk_business_units_parent_id_business_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_units')),
    sa.UniqueConstraint('name', name=op.f('uq_business_units_name'))
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('Mtr', 'PC', 'MT', name='unitofmeasure'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_unit_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_customers_business_unit_id_business_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('products')
    op.drop_table('business_units')
    # ### end Alembic commands ###
