"""coverage scope defaults -- the platform-wide status/profile filter, made adjustable

Adds ONE table, ``coverage_scope_defaults``, holding at most one row.

``app.engines.coverage`` decides which demand it evaluates at all from a STATUS filter
(which selects whole wells, because demand status lives on ``Well.demand_status``) and
a PROFILE filter (which selects lines, cutting inside a well). Both were Python
constants -- ``DEFAULT_STATUS_FILTER`` and ``DEFAULT_PROFILE_FILTER`` -- adjustable
only by a code change and a deploy. The product owner asked for them to be adjustable
from the Administration screen, so they now have a row. See
``app.models.coverage_scope`` for the full statement of the shape and
``app.engines.coverage_scope`` for how the constants became the FALLBACK rather than
being deleted.

PURELY ADDITIVE, AND THE TABLE STARTS EMPTY
-------------------------------------------
One new table. No existing table is altered, no existing column is touched, and --
this is the part worth reading -- NO ROW IS INSERTED.

That is deliberate, not an omission. An empty table means "nobody has adjusted the
scope", and ``app.engines.coverage_scope`` then resolves the original module constants.
Back-filling a row carrying the shipped values would be strictly worse in two ways:

  * it would make "never adjusted" indistinguishable from "adjusted, and set back to
    the shipped values" -- a distinction the Administration screen serves
    (``persisted``) precisely because an administrator may legitimately do the latter;
  * it would create a second home for values the code already states, so a future
    change to the shipped default would silently apply only to databases created after
    it, while every existing database kept the back-filled copy. The constants are the
    fallback, not a duplicate to keep in sync.

So this migration is safe to run against a database an application server is holding
open, and a database upgraded to this revision behaves EXACTLY as it did before --
identical verdicts, identical scope -- until somebody uses the new endpoint.

NO NEW ENUM TYPE, AND NO DUPLICATE-TYPE TRAP
--------------------------------------------
The known autogenerate trap in this project (see ``7ebf91b5526c_initial_schema``,
``c4f1a90b7de2_scenario_planning``, ``b7f4c1a92e30_demand_import_staging`` and the note
in ``c8e37b45d1a0_customer_owned_inventory``) is that alembic emits a bare
``sa.Enum(..., name=...)`` inline in every ``create_table`` that mentions it, so on
postgres the SECOND such table raises ``DuplicateObject``. ``DATABASE_URL`` defaults to
postgres, so raw autogenerated output carrying an inline enum would be unrunnable in
production.

It cannot bite here, and again by design rather than by luck. Neither filter column is
an enum column, because neither stores a VALUE -- each stores a SET ("Confirmed", or
"Planned,Confirmed"). A SQLAlchemy enum column holds one member and therefore cannot
express what is being stored at all, and an association table of (setting, status) rows
would be three tables and a join for a fact that is two short lists. They are
comma-separated ``DemandStatus`` / ``DemandProfile`` values in a ``String``, parsed and
validated in exactly one place (``app.engines.coverage_scope``), which raises on an
unknown token rather than skipping it.

Consequently ``_create_enum_types`` / ``_drop_enum_types`` are absent from this
revision because there is genuinely nothing for them to do. The two existing enum
types ``demandstatus`` and ``demandprofile`` are untouched and unreferenced here.

THE SINGLETON CHECK CONSTRAINT
------------------------------
``ck_coverage_scope_defaults_singleton`` pins ``id`` to the literal ``'platform'``.
This is the singleton guarantee expressed in the DATABASE and not merely in the
accessor, and it earns its place: two rows here would mean two platform-wide defaults,
and whichever one a query happened to return first would decide every coverage verdict
on the platform -- unexplainably, and potentially differently between two servers
reading the same data. A named CHECK constraint is used rather than a partial unique
index because the rule is about the VALUE of the primary key, which is exactly what
CHECK expresses, and because it is portable to sqlite (the dev database) unchanged.

``updated_at`` carries a ``server_default`` of ``now()`` so a row inserted by anything
other than the engine still records when. The engine sets it explicitly anyway, because
a ``server_default`` is only visible after a refresh and the change payload has to
report the value it just wrote.

Revision ID: d9c4a2b71e58
Revises: c8e37b45d1a0
Create Date: 2026-08-05 16:10:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9c4a2b71e58'
down_revision: Union[str, Sequence[str], None] = 'c8e37b45d1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: Kept in step with ``app.models.coverage_scope.SINGLETON_ID``. Written as a literal
#: rather than imported: a migration must describe the schema as it was at THIS
#: revision, and importing the application constant would silently rewrite history the
#: day somebody changed it.
SINGLETON_ID = 'platform'


def upgrade() -> None:
    """Create the settings table. Insert nothing -- see the module docstring."""
    op.create_table(
        'coverage_scope_defaults',
        sa.Column('id', sa.String(length=36), nullable=False),
        # Comma-separated DemandStatus values, e.g. 'Confirmed' or 'Planned,Confirmed'.
        sa.Column('status_filter', sa.String(), nullable=False),
        # Comma-separated DemandProfile values, e.g. 'Primary,Contingency'.
        sa.Column('profile_filter', sa.String(), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            f"id = '{SINGLETON_ID}'",
            name='ck_coverage_scope_defaults_singleton',
        ),
    )


def downgrade() -> None:
    """Drop the table.

    A real downgrade, not a ``pass``.

    WHAT IS LOST, AND WHY IT IS RECOVERABLE
    ---------------------------------------
    Only the administrator's ADJUSTMENT. Dropping this table does not lose a coverage
    verdict, a demand line or an inventory position -- it removes the row that said
    "evaluate a different scope than the shipped one", after which
    ``app.engines.coverage_scope`` resolves ``DEFAULT_STATUS_FILTER`` /
    ``DEFAULT_PROFILE_FILTER`` again. Those live in code, so the fallback survives the
    downgrade intact and the platform is left in the exact state it shipped in.

    This is genuinely unlike ``c8e37b45d1a0``'s downgrade, which destroys customer-owned
    inventory that has no other source. Here the only irrecoverable fact is WHICH scope
    somebody had chosen and when; re-applying ``upgrade`` and re-saving the scope from
    the Administration screen restores it completely.

    IT IS NOT A NO-OP, THOUGH, AND THE EFFECT IS SILENT
    --------------------------------------------------
    If a scope WAS persisted and differed from the shipped one, every coverage verdict
    on the platform reverts to being computed under the shipped scope -- and the stored
    ``CoverageResult`` rows do NOT revert with it, because nothing here recomputes them.
    They keep describing the dropped scope until the next natural recompute of each
    customer (any demand revision, well-status change, customer-owned upload, or a
    fresh save from the Administration screen).

    That window is the one hazard of this downgrade, so it is stated rather than
    implied: after downgrading a database whose scope had been adjusted, trigger a
    recompute -- the simplest honest way is to re-``upgrade``, re-save the intended
    scope, and then decide -- or accept that the coverage grid is briefly answering the
    dropped scope's question.
    """
    op.drop_table('coverage_scope_defaults')
