"""demand import: staging baseline + override approval for conflicting rows

Adds SIX nullable-or-defaulted columns to ``demand_import_rows`` so that a staged
row can (a) be compared against the live demand book it would land on and (b) carry
an explicit human approval for overriding a disagreement. See
``app.models.demand_import.DemandImportRow`` for the column-by-column reasoning and
``app.engines.demand_import.detect_conflict`` for what counts as a conflict.

    baseline_revision_no   the matched demand line's ``current_revision_no`` at the
    baseline_quantity      moment of staging, plus the two values a reviewer needs
    baseline_ros_date      to see that the ground moved. All NULL on a row that
                           matched no line -- a genuinely new demand line has no
                           prior live value to have drifted from.
    override_approved      the SECOND decision, distinct from accept/skip: "I have
    override_approved_at   seen that this row disagrees with live data and I approve
    override_approved_by   overriding that". ``_by`` is ATTRIBUTION ONLY.

THERE IS DELIBERATELY NO ``is_conflict`` COLUMN
----------------------------------------------
A conflict is a statement about the relationship between a staged row and a book
that keeps moving after staging. A stored flag would be the answer to a question
asked at the wrong moment, and the review screen would render a stale verdict --
worse than none, because it looks authoritative. So the flag is DERIVED on every
read by one detector, and this revision persists only the FACT the detector needs
(the baseline) and the DECISION a human made about it (the approval).

PURELY ADDITIVE
---------------
Six ``ADD COLUMN``s on one existing table. No column is dropped, renamed or
retyped, no other table is touched, and no data is migrated -- so this is safe to
run against a database an application server is holding open, and a database
upgraded to this revision behaves EXACTLY as it did before until somebody uploads a
new batch.

BACK-FILL: NOTHING, AND THAT IS CORRECT
---------------------------------------
Rows staged by an earlier build get NULL baselines and ``override_approved = false``.
Both are the honest values and neither could be invented:

  * A baseline is "what the matched line looked like at staging". That moment has
    passed and was never recorded, so any value written here would be a guess.
    Writing today's ``current_revision_no`` would be the tempting guess and the worst
    one -- it would assert that nothing has drifted since staging, which is precisely
    the claim the column exists to check.
  * ``override_approved = false`` is not a gap, it is true: nobody approved anything,
    because there was nothing to approve until now.

The consequence is stated rather than hidden: a batch staged before this migration
and applied after it cannot raise a CONCURRENT_REVISION conflict (its baseline is
NULL, and ``detect_conflict`` requires one), so such a row applies exactly as it
would have before. It CAN still raise a WELL_DEMAND_STATUS conflict, which is
computed entirely from the row's own ``raw_status`` / ``status`` against the well's
current value and needs no baseline at all. Old batches therefore lose the drift
check they never had and gain the status check immediately.

NO NEW ENUM TYPE, SO THE DUPLICATE-TYPE TRAP CANNOT BITE
--------------------------------------------------------
The known autogenerate trap in this project (see ``7ebf91b5526c_initial_schema``,
``c4f1a90b7de2_scenario_planning`` and ``b7f4c1a92e30_demand_import_staging``) is
that alembic emits a bare ``sa.Enum(..., name=...)`` inline per table, so on
postgres the second such statement raises ``DuplicateObject``. ``DATABASE_URL``
defaults to postgres, so raw autogenerated output carrying an inline enum would be
unrunnable in production.

It cannot bite here, by design rather than by luck: NONE of the six columns is an
enum. The conflict KIND (``WellDemandStatus`` / ``ConcurrentRevision``) is the
obvious candidate and is deliberately not stored at all -- see above -- so there is
nothing for a type to constrain, and a database enum for it would give assurance
about a value the schema never sees. ``_create_enum_types`` / ``_drop_enum_types``
are consequently absent because there is genuinely nothing for them to do.

``override_approved`` AND ITS SERVER DEFAULT
-------------------------------------------
Declared NOT NULL, which needs a ``server_default`` so the ADD COLUMN can fill
existing rows. The default is KEPT rather than dropped afterwards: it makes the
column's floor a property of the schema, so a row inserted by any route -- a future
raw-SQL fixture, a bulk load -- is un-approved rather than NULL. It produces no
autogenerate drift because ``alembic/env.py`` does not enable
``compare_server_default``; the model's Python-side ``default=False`` and this
server default agree on the value regardless, so there is no way for the two to
disagree.

``render_as_batch=True`` is set in ``alembic/env.py``, so ``batch_alter_table`` is
used for sqlite's benefit (it rebuilds the table) and is a plain ALTER on postgres.

Revision ID: f1a83c60d27b
Revises: d9c4a2b71e58
Create Date: 2026-08-05 23:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1a83c60d27b'
down_revision: Union[str, Sequence[str], None] = 'd9c4a2b71e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the three baseline columns and the three approval columns."""
    with op.batch_alter_table('demand_import_rows') as batch:
        batch.add_column(
            sa.Column('baseline_revision_no', sa.Integer(), nullable=True)
        )
        batch.add_column(sa.Column('baseline_quantity', sa.Float(), nullable=True))
        batch.add_column(
            sa.Column('baseline_ros_date', sa.DateTime(), nullable=True)
        )
        batch.add_column(
            sa.Column(
                'override_approved',
                sa.Boolean(),
                server_default=sa.false(),
                nullable=False,
            )
        )
        batch.add_column(
            sa.Column('override_approved_at', sa.DateTime(), nullable=True)
        )
        batch.add_column(
            sa.Column('override_approved_by', sa.String(), nullable=True)
        )


def downgrade() -> None:
    """Drop all six columns. A real downgrade, not a ``pass``.

    WHAT IS LOST, AND WHETHER IT MATTERS
    ------------------------------------
    Only STAGING data, and only for batches not yet applied. Nothing here is demand:
    a `DemandImportRow` is a parsed spreadsheet line plus decisions about it, and the
    demand book, its revision history and its impact records are all untouched by
    this revision in either direction. Downgrading cannot lose a quantity anybody
    ordered.

    What it does lose, for any batch still in Staged:

      * the BASELINE, so a concurrent revision landing between staging and apply
        becomes undetectable again and such a row would silently overwrite somebody
        else's change -- the lost-update problem this revision exists to surface;
      * every OVERRIDE APPROVAL already recorded, including who gave it and when.

    Neither is recoverable by re-running anything: there is no upstream feed for a
    human decision, and the staging moment has passed. The practical consequence is
    that after a downgrade an in-flight batch must be re-reviewed -- and, because the
    approval column is gone, the running code (which no longer gates) would apply its
    conflicting rows without asking. So APPLY OR DISCARD ANY STAGED BATCH BEFORE
    DOWNGRADING; a re-upload of the same workbook restages it correctly against
    whatever the book says at that point, which is the honest starting position
    anyway.

    Re-running ``upgrade`` restores the schema and nothing else.
    """
    with op.batch_alter_table('demand_import_rows') as batch:
        batch.drop_column('override_approved_by')
        batch.drop_column('override_approved_at')
        batch.drop_column('override_approved')
        batch.drop_column('baseline_ros_date')
        batch.drop_column('baseline_quantity')
        batch.drop_column('baseline_revision_no')
